name: epitech
description: Oros Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  awesome_icons: ^1.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
